/*
 * Copyright (c) 2025 Marco Marini, marco.marini@mmarini.org
 *
 *  Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 *    END OF TERMS AND CONDITIONS
 *
 */

package org.mmarini.qucomp.compiler;

import io.reactivex.rxjava3.functions.BiConsumer;
import io.reactivex.rxjava3.functions.Consumer;
import org.mmarini.qucomp.apis.Bra;
import org.mmarini.qucomp.apis.Complex;
import org.mmarini.qucomp.apis.Ket;

import java.util.*;

import static java.lang.Math.abs;
import static java.util.Objects.requireNonNull;

/**
 * Executes the code generated by compiler
 */
public class Processor {
    private static final Map<String, BiConsumer<Processor, SourceContext>> FUNCTIONS_MAP = Map.of(
            "sqrt", Processor::sqrt
    );

    /**
     * Executes the command
     *
     * @param command the command
     */
    private void executeCommand(Command command) throws Throwable {
        switch (command) {
            case null -> throw new NullPointerException();
            case Command.PushInt push -> stack.offer(push.value());
            case Command.PushString push -> stack.offer(push.value());
            case Command.PushComplex push -> stack.offer(push.value());
            case Command.PushKet push -> stack.offer(push.value());
            case Command.Assign ignored -> {
                Object value = stack.removeLast();
                String id = popString(command.sourceContext());
                variables.put(id, value);
                stack.offer(value);
            }
            case Command.RetrieveVar ignored -> {
                String id = popString(command.sourceContext());
                Object value = variables.get(id);
                if (value == null) {
                    throw command.sourceContext().exception("Variable \"%s\" not found", id);
                }
                stack.offer(value);
            }
            case Command.Multiply ignored -> {
                Object right = stack.removeLast();
                Object left = stack.removeLast();
                Object result = switch (left) {
                    case Integer value -> multiply(value, right, command);
                    case Complex value -> multiply(value, right, command);
                    case Ket value -> multiply(value, right, command);
                    case Bra value -> multiply(value, right, command);
                    default -> throw command.sourceContext().exception("Invalid left operand %s", left);
                };
                stack.offer(result);
            }
            case Command.Add ignored -> {
                Object right = stack.removeLast();
                Object left = stack.removeLast();
                Object result = switch (left) {
                    case Integer value -> add(value, right, command);
                    case Complex value -> add(value, right, command);
                    case Ket value -> add(value, right, command);
                    case Bra value -> add(value, right, command);
                    default -> throw command.sourceContext().exception("Invalid left operand %s", left);
                };
                stack.offer(result);
            }
            case Command.Sub ignored -> {
                Object right = stack.removeLast();
                Object left = stack.removeLast();
                Object result = switch (left) {
                    case Integer value -> sub(value, right, command);
                    case Complex value -> sub(value, right, command);
                    case Ket value -> sub(value, right, command);
                    case Bra value -> sub(value, right, command);
                    default -> throw command.sourceContext().exception("Invalid left operand %s", left);
                };
                stack.offer(result);
            }
            case Command.Divide ignored -> {
                Object right = stack.removeLast();
                Object left = stack.removeLast();
                Object result = switch (left) {
                    case Integer value -> divide(value, right, command);
                    case Complex value -> divide(value, right, command);
                    case Ket value -> divide(value, right, command);
                    case Bra value -> divide(value, right, command);
                    default -> throw command.sourceContext().exception("Invalid left operand %s", left);
                };
                stack.offer(result);
            }
            case Command.Negate cmd -> stack.offer(negate(cmd));
            case Command.Conj cmd -> stack.offer(conj(cmd));
            case Command.Consume ignored -> consumer.accept(stack.pop());
            case Command.CallFunction call -> {
                BiConsumer<Processor, SourceContext> func = FUNCTIONS_MAP.get(call.value());
                if (func == null) {
                    throw command.sourceContext().exception("Invalid function %s", call.value());
                }
                func.accept(this, call.sourceContext());
            }
            default -> throw command.sourceContext().exception("Invalid command %s", command);
        }
    }

    final Map<String, Object> variables;
    final Deque<Object> stack;
    private final Consumer<Object> consumer;

    /**
     * Creates the processor
     *
     * @param consumer the expression result consumer
     */
    public Processor(Consumer<Object> consumer) {
        this.consumer = requireNonNull(consumer);
        this.stack = new LinkedList<>();
        this.variables = new HashMap<>();
    }

    private Object add(int left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left + value;
            case Complex value -> Complex.create(left).add(value);
            case Ket value -> throw command.sourceContext().exception("Right operand must not be a ket %s", value);
            case Bra value -> throw command.sourceContext().exception("Right operand must not be a bra %s", value);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object add(Complex left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left.add(value);
            case Complex value -> left.add(value);
            case Ket value -> throw command.sourceContext().exception("Right operand must not be a ket %s", value);
            case Bra value -> throw command.sourceContext().exception("Right operand must not be a bra %s", value);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object add(Ket left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value ->
                    throw command.sourceContext().exception("Right operand must not be a complex %s", value);
            case Complex value ->
                    throw command.sourceContext().exception("Right operand must not be a complex %s", value);
            case Ket value -> left.extend(value.values().length)
                    .add(value.extend(left.values().length));
            case Bra value -> throw command.sourceContext().exception("Right operand must not be a bra %s", value);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object add(Bra left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value ->
                    throw command.sourceContext().exception("Right operand must not be a complex %s", value);
            case Complex value ->
                    throw command.sourceContext().exception("Right operand must not be a complex %s", value);
            case Ket value -> throw command.sourceContext().exception("Right operand must not be a ket %s", value);
            case Bra value -> left.extend(value.values().length)
                    .add(value.extend(left.values().length));
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object conj(Command.Conj cmd) throws ParseException {
        Object arg = stack.removeLast();
        return switch (arg) {
            case Integer val -> val;
            case Complex val -> val.conj();
            case Ket val -> val.conj();
            case Bra val -> val.conj();
            case null, default -> throw cmd.sourceContext().exception("Undefined stack object %s", arg);
        };
    }

    private Object divide(int left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left % value == 0
                    ? left / value
                    : Complex.create(left).div(Complex.create(value));
            case Complex value -> Complex.create(left).div(value);
            case Ket value -> {
                Bra bra = value.conj();
                yield bra.mul(bra.mul(value).inv().mul(left));
            }
            case Bra value -> {
                Ket ket = value.conj();
                yield ket.mul(value.mul(ket).inv().mul(left));
            }
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object divide(Complex left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left.div(Complex.create(value));
            case Complex value -> left.div(value);
            case Ket value -> {
                Bra bra = value.conj();
                yield bra.mul(bra.mul(value).inv().mul(left));
            }
            case Bra value -> {
                Ket ket = value.conj();
                yield ket.mul(value.mul(ket).inv().mul(left));
            }
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object divide(Bra left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left.mul(1f / value);
            case Complex value -> left.mul(value.inv());
            case Ket value -> throw command.sourceContext().exception("Right operand must not be a ket %s", value);
            case Bra value -> {
                left = left.extend(value.values().length);
                value = value.extend(left.values().length);
                Ket ket = value.conj();
                yield left.mul(ket).mul(value.mul(ket).inv());
            }
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object divide(Ket left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left.mul(1f / value);
            case Complex value -> left.mul(value.inv());
            case Ket value -> {
                left = left.extend(value.values().length);
                value = value.extend(left.values().length);
                Bra bra = value.conj();
                yield bra.mul(left).mul(bra.mul(value).inv());
            }
            case Bra value -> throw command.sourceContext().exception("Right operand must not be a bra %s", value);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    /**
     * Executes the code
     *
     * @param code the code
     */
    public void executeCode(List<Command> code) throws Throwable {
        for (Command command : code) {
            executeCommand(command);
        }
    }

    private void sqrt(SourceContext context) throws ParseException {
        Object value = stack.removeLast();
        Complex result = switch (value) {
            case Integer val -> Complex.create((float) Math.sqrt(val));
            case Complex val when abs(val.module()) == 0 -> Complex.zero();
            case Complex val when val.real() >= 0 -> {
                float reDelta = val.real() + val.module();
                float re = (float) Math.sqrt(reDelta / 2);
                float im = (float) (val.im() / Math.sqrt(2 * reDelta));
                yield new Complex(re, im);
            }
            case Complex val -> {
                float reDelta = -val.real() + val.module();
                float re = (float) (val.im() / Math.sqrt(2 * reDelta));
                float im = (float) Math.sqrt(reDelta / 2);
                yield new Complex(re, im);
            }
            case Bra val -> throw context.exception("Argument must not be a bra %s", val);
            case Ket val -> throw context.exception("Argument must not be a ket %s", val);
            default -> throw context.exception("Invalid argument %s", value);
        };
        stack.offer(result);
    }

    private Object multiply(Bra left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left.mul(value);
            case Complex value -> left.mul(value);
            case Ket value -> left.extend(value.values().length)
                    .mul(value.extend(left.values().length));
            case Bra value -> throw command.sourceContext().exception("Right operand must not be a bra %s", value);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object multiply(Ket left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left.mul(value);
            case Complex value -> left.mul(value);
            case Ket value -> throw command.sourceContext().exception("Right operand must not be a ket %s", value);
            case Bra value -> throw command.sourceContext().exception("Right operand must not be a bra %s", value);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object multiply(int left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left * value;
            case Complex value -> value.mul(left);
            case Ket value -> value.mul(left);
            case Bra value -> value.mul(left);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object multiply(Complex left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left.mul(value);
            case Complex value -> value.mul(left);
            case Ket value -> value.mul(left);
            case Bra value -> value.mul(left);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object negate(Command.Negate cmd) throws ParseException {
        Object arg = stack.removeLast();
        return switch (arg) {
            case Integer val -> -val;
            case Complex val -> val.neg();
            case Ket val -> val.neg();
            case Bra val -> val.neg();
            case null, default -> throw cmd.sourceContext().exception("Undefined stack object %s", arg);
        };
    }

    /**
     * Returns the string value in the stack
     *
     * @param context the report token
     */
    private String popString(SourceContext context) throws ParseException {
        Object value = stack.removeLast();
        if (value instanceof String str) {
            return str;
        }
        throw context.exception("Value %s is not a string", value);
    }

    private Object sub(Bra left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value ->
                    throw command.sourceContext().exception("Right operand must not be a complex %s", value);
            case Complex value ->
                    throw command.sourceContext().exception("Right operand must not be a complex %s", value);
            case Ket value -> throw command.sourceContext().exception("Right operand must not be a ket %s", value);
            case Bra value -> left.extend(value.values().length)
                    .sub(value.extend(left.values().length));
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object sub(Complex left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left.sub(value);
            case Complex value -> left.sub(value);
            case Ket value -> throw command.sourceContext().exception("Right operand must not be a ket %s", value);
            case Bra value -> throw command.sourceContext().exception("Right operand must not be a bra %s", value);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object sub(Ket left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value ->
                    throw command.sourceContext().exception("Right operand must not be a complex %s", value);
            case Complex value ->
                    throw command.sourceContext().exception("Right operand must not be a complex %s", value);
            case Ket value -> left.extend(value.values().length)
                    .sub(value.extend(left.values().length));
            case Bra value -> throw command.sourceContext().exception("Right operand must not be a bra %s", value);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }

    private Object sub(int left, Object right, Command command) throws ParseException {
        return switch (right) {
            case Integer value -> left - value;
            case Complex value -> Complex.create(left).sub(value);
            case Ket value -> throw command.sourceContext().exception("Right operand must not be a ket %s", value);
            case Bra value -> throw command.sourceContext().exception("Right operand must not be a bra %s", value);
            default -> throw command.sourceContext().exception("Invalid right operand %s", right);
        };
    }
}
